/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElAlert: typeof import('element-plus/es')['ElAlert']
  const ElForm: typeof import('element-plus/es')['ElForm']
}
