/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ComponentButtonGroup: typeof import('./src/components/component-button-group/src/component-button-group.vue')['default']
    ComponentDialog: typeof import('./src/components/component-dialog/src/component-dialog.vue')['default']
    ComponentForm: typeof import('./src/components/component-form/src/component-form.vue')['default']
    ComponentFormItem: typeof import('./src/components/component-form-item/src/component-form-item.vue')['default']
    ComponentTable: typeof import('./src/components/component-table/src/component-table.vue')['default']
    CustomComponent: typeof import('./src/components/utils/CustomComponent.vue')['default']
    CustomForm: typeof import('./src/components/utils/CustomForm.vue')['default']
    CustomFormChild: typeof import('./src/components/utils/CustomFormChild.vue')['default']
    CustomFormComponent: typeof import('./src/components/utils/CustomForm.vue')['default']
    CustomFormItem: typeof import('./src/components/utils/CustomFormItem.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElComponentForm: typeof import('./src/components/Form/src/ElComponentForm.vue')['default']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormComponent: typeof import('./src/components/element-plus/el-form-component/src/el-form-component.vue')['default']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    ElWwitch: typeof import('element-plus/es')['ElWwitch']
    ErrorPageTypewriter: typeof import('./src/components/error-page/type-writer/src/ErrorPageTypewriter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Src: typeof import('./src/components/element-plus/element-plus-component/src/index.vue')['default']
    TypeWriter: typeof import('./src/components/error-page/type-writer.vue')['default']
  }
}
